### ISSUE TITLE
Front-end view for creating a training job

### ISSUE THREAD

**Issue by harrykeightley** [CoEDL/elpiscloud#22]
## TODO
- [x] When users visit /train, they should first of all be prompted to select a dataset to train with.
- [x] If the user has datasets but they are not yet processed, they should still see datasets, but there should be something to inform the user that they cannot select this until processing has completed.
- [x] If there are no datasets at all for a certain user, there should be an option to navigate to the datasets page to create one.
- [x] After selecting a dataset, the user should be provided with training options similar to the desktop version of elpis.
- [x] When a the options and dataset have been selected, the frontend should create a new training job in firestore with information about the date, dataset involved, and selected options.
